global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:

  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node-exporter:9100']

  - job_name: 'nextcloud-exporter'
    static_configs:
      - targets: ['nextcloud-exporter:9205']

  - job_name: 'docker_sd'
    docker_sd_configs:
      - host: tcp://host.docker.internal:2375