global:
  scrape_interval: 30s
  scrape_timeout: 10s

# rule_files:
#   - alert.yml

# alerting:
#   alertmanagers:
#     - scheme: http
#       static_configs:
#         - targets: [ 'alertmanager:9093' ]

scrape_configs:
  # - job_name: 'prometheus' 
  #   static_configs: 
  #     - targets: ['127.0.0.1:9090']

  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node-exporter:9100']


  # - job_name: 'haproxy-exporter' 
  #   static_configs: 
  #     - targets: ['haproxy-exporter:9101']
  
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['host.docker.internal:9323']

  # - job_name: 'docker_sd'
  #   docker_sd_configs:
  #     - host: tcp://host.docker.internal:2375

  # - job_name: 'http_sd'
  #   http_sd_configs:
  #     - url: http://HAProxy/http_sd.json


